stages:
  - name: Build and Push
    steps:
      - publishImageConfig:
          dockerfilePath: ./docker/Dockerfile
          buildContext: ./
          tag: docker.dev.folio.org/platform-complete:core-functional-latest
          pushRemote: true
          registry: docker.dev.folio.org
        env:
          PLUGIN_BUILD_ARGS_FROM_ENV: OKAPI_URL, TENANT_ID
        envFrom:
          - sourceName: tenant-config
            sourceKey: TENANT_ID
          - sourceName: tenant-config
            sourceKey: OKAPI_URL
        cpuRequest: 100m
        cpuLimit: 1500m
        memoryRequest: 100Mi
        memoryLimit: 8Gi
timeout: 60
branch:
  include:
    - core-functional-rancher
notification: {}
